export const supabaseAdminKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sb2dtcmViZGV4bWxka2Vrc2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxNjI1NzYsImV4cCI6MjA5OTczODU3Nn0.2WDc_IQ19bhpcnNFsdusngUCELHkpmgDet_fXjXKQBA
export const key = process.env.NEXT_PUBLIC_SUPABASE_SERVICE_KEY;
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sb2dtcmViZGV4bWxka2Vrc2RlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDE2MjU3NiwiZXhwIjoyMDk5NzM4NTc2fQ.m036mm-uqQ8VBKLrH2Yx6kn-iX9BLmfMYhOpCqRkxg0";
